Billy/verification
ryanata/password-manager pull request #20
Opened 2022-11-02 23:38 UTC by billyfurie

**Verification API**

This endpoint handles the verification codes for account verification, resetting password, and any general authentication using a code sent to the user.

Allows for creation of the code (which entails sending the code to the user via email or phone
Allows for verification of the code sent to the user

I have documentation currently in-progress in Postman for this and I will be happy to help with integrating of this endpoint into the frontend.

2022-11-02 23:39 UTC, billyfurie commented on backend/routes/userRoutes.js
> +    loginUser
I actually don't know when this change was made. This could be left as the original.

2022-11-03 03:38 UTC, ryanata commented
Pull main and resolve conflicts before merge.

2022-11-03 04:12 UTC, ryanata requested changes
Overall, looks good! Don't forget to resolve comments

2022-11-06 15:56 UTC, ryanata approved these changes
lgtm

2022-11-07 01:50 UTC, merged